version: 1.0
provider:
  name: openfaas
  gateway: https://cg.sergevas.dev

functions:
  submit-sample:
    lang: python3
    handler: ./submit-sample
    image: cgsergevas/submit-sample:latest
    environment:
      influx_host: influxdb
      influx_port: 8086
      influx_db: defaultdb
      write_debug: true
      read_debug: true
      combine_output: false
    secrets:
      - influx-user
      - influx-pass
